### ISSUE TITLE
release is empty

### ISSUE THREAD

**Issue by KsAmJ** [Keeperdy/PS4-Host-ESP8266-Firmware-2in1-for-4.55-5.05-5.07#5]
i cant find the release you made for the 2.1.4

**Comment by Keeperdy** [comment]
'cause it has not been relaesed yet :)

**Comment by KsAmJ** [comment]
why did u remove app2usb?

**Comment by Keeperdy** [comment]
'cause it can be done via PS4 original tools. Do you need it?

**Comment by KsAmJ** [comment]
original tools can't run fake packages per modded warfare video

https://youtu.be/bJd4-ZIN8EA?t=40

also have limitations on the drive

**Comment by Keeperdy** [comment]
Please, read about HEN External HDD support

**Comment by KsAmJ** [comment]
unfortunately i can't find clear sources about that and anyway i see people still using it till now so i recommend to include it in your releases as it might draw some people off it.

**Comment by Keeperdy** [comment]
OK
